
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'my_new_project'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'default'

# These configurations specify where dbt should look for different types of files.
# The `source-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/ directory
# as tables. These settings can be overridden in the individual model files
# using the `{{ config(...) }}` macro.
models:
  my_new_project:
    # Applies to all files under models/example/
    ROne_Analytics_Staging:
      materialized: table
      #+database: "{{ 'DBT' if target.name == 'dev' else 'PROD_DETAIL' }}"
      #+schema: "{{ 'DBT_FARONOVICH' if target.name == 'dev' else 'BETS' }}"
      +database: 'postgres'
      +schema: 'ro_data'
      +transient: false
      +post-hook: 'grant select on {{ this }} to group "RO_Read_Only_access"'
      +post-hook: 'grant select on {{ this }} to group "RO_Read_Write_access"'
    ROne_Analytics_Staging_incremental_load:
      materialized: incremental
      #+database: "{{ 'DBT' if target.name == 'dev' else 'PROD_DETAIL' }}"
      #+schema: "{{ 'DBT_FARONOVICH' if target.name == 'dev' else 'BETS' }}"
      +database: 'postgres'
      +schema: 'ro_data'
      +transient: false
      +post-hook: 'grant select on {{ this }} to group "RO_Read_Only_access"'
      +post-hook: 'grant select on {{ this }} to group "RO_Read_Write_access"'